import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ppm.vistaar.us/vistaarppm/ppmOnVWUF/VistaarPPM/index.html#TS_Entry');
  await page.goto('https://ppm.vistaar.us/vistaarppm/login.php');
  await page.locator('input[name="email_id"]').click();
  await page.locator('input[name="email_id"]').fill('Employee@1102');
  await page.locator('input[name="email_id"]').press('Tab');
  await page.locator('input[name="email_id"]').click();
  await page.locator('input[name="email_id"]').press('Control+a');
  await page.locator('input[name="email_id"]').fill('gharayan');
  await page.locator('input[name="email_id"]').press('Tab');
  await page.locator('input[name="pswd"]').fill('Employee@1102');
  await page.locator('input[name="pswd"]').press('Tab');
  await page.getByRole('button', { name: 'Submit' }).press('Enter');
  await page.getByRole('button', { name: 'Timesheet' }).click();
  await page.getByRole('menuitem', { name: 'Timesheet Entry' }).click();
  await page.getByLabel('Week').click();
  await page.getByRole('option', { name: '-Jan-24 to 28-Jan-24 (N)' }).click();
  await page.locator('#tableview-1099-record-423 > tbody > .x-grid-row > td:nth-child(2)').click();
  await page.locator('#TSEntryGrd_cmbProject-trigger-picker').click();
  await page.getByRole('option', { name: 'Century Communities - Release' }).locator('div').click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('NA');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('NA');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('NA');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('NumLock');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('ok');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');
  await page.locator('#btnTSEntry_AddNewRow').click();
  await page.locator('#tableview-1099-record-616 > tbody > .x-grid-row > td:nth-child(2) > .x-grid-cell-inner').click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').fill('Pre');
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').fill('Buil');
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').press('Tab');
  await page.locator('#ext-element-121').click();
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').click();
  await page.locator('#combobox-1395-trigger-picker').click();
  await page.getByRole('option', { name: 'NA - Demo Preparation' }).click();
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').press('Tab');
  await page.locator('#combobox-1398-trigger-picker').click();
  await page.getByRole('option', { name: 'AWS Setup Optimization' }).click();
  await page.locator('#ext-element-116 > td:nth-child(5) > .x-grid-cell-inner').click();
  await page.locator('#combobox-1401-trigger-picker').click();
  await page.locator('#combobox-1401-trigger-picker').click();
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').fill('NA');
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').fill('ok');
  await page.getByRole('row', { name: 'Presales Internal (Dept : Pre' }).getByLabel('').press('Tab');
});