import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ppm.vistaar.us/vistaarppm/ppmOnVWUF/VistaarPPM/index.html#TS_Entry');
  await page.goto('https://ppm.vistaar.us/vistaarppm/login.php');
  await page.locator('input[name="email_id"]').click();
  await page.locator('input[name="email_id"]').fill('gharayan');
  await page.locator('input[name="email_id"]').press('Tab');
  await page.locator('input[name="pswd"]').fill('Employee@1102');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Timesheet' }).click();
  await page.getByRole('menuitem', { name: 'Timesheet Entry' }).click();
  await page.getByRole('button', { name: 'Timesheet' }).press('NumLock');
  await page.locator('#cmbTSEntry_SelectWeek-trigger-picker').click();
  await page.getByRole('option', { name: '-Jan-24 to 28-Jan-24 (N)' }).click();
  await page.locator('#ext-element-74').click();
  await page.locator('#TSEntryGrd_cmbProject-trigger-picker').click();
  await page.locator('#TSEntryGrd_cmbProject-trigger-picker').click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').press('NumLock');
  await page.locator('#cmbTSEntry_SelectWeek-trigger-picker').click();
  await page.getByRole('option', { name: '-Jan-24 to 28-Jan-24 (N)' }).click();
  await page.locator('td:nth-child(2) > .x-grid-cell-inner').first().click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').click();
  await page.locator('#TSEntryGrd_cmbProject-trigger-picker').click();
  await page.getByText('Century Communities - Release').click();
  await page.locator('td:nth-child(3) > .x-grid-cell-inner').first().click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('NumLock');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.locator('td:nth-child(4) > .x-grid-cell-inner').first().click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill(' ');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Alt+CapsLock');
  await page.locator('#combobox-1372-trigger-picker').click();
  await page.locator('#combobox-1372-trigger-picker').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('Ge');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').press('Tab');   
  await page.locator('#combobox-1372-trigger-picker').click();
  await page.locator('#btnTSEntry_AddNewRow').click();
  await page.locator('#tableview-1071-record-545 > tbody > .x-grid-row > td:nth-child(2) > .x-grid-cell-inner').click();
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').fill('Ce');
  await page.getByRole('row', { name: '0 0 0 0 0 0 0 0', exact: true }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release 1.0 (Dept : SDG) 0 0 0 0 0 0 0' }).getByLabel('').fill('N');
  await page.getByRole('row', { name: 'Century Communities - Release 1.0 (Dept : SDG) 0 0 0 0 0 0 0' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release 1.0 (Dept : SDG) Build / Construction -' }).getByLabel('').fill('N');
  await page.getByRole('row', { name: 'Century Communities - Release 1.0 (Dept : SDG) Build / Construction -' }).getByLabel('').press('Tab');
  await page.getByRole('row', { name: 'Century Communities - Release 1.0 (Dept : SDG) Build / Construction -' }).getByLabel('').fill('');
  await page.locator('#combobox-1372-trigger-picker').click();
  await page.getByRole('option', { name: 'GCMM Configuration' }).click();
});