import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ppm.vistaar.us/vistaarppm/ppmOnVWUF/VistaarPPM/index.html#TS_Entry');
  await page.goto('https://ppm.vistaar.us/vistaarppm/login.php');
  await page.locator('input[name="email_id"]').click();
  await page.locator('input[name="email_id"]').fill('gharayan');
  await page.locator('input[name="email_id"]').press('Tab');
  await page.locator('input[name="pswd"]').fill('Employee@1102');
  await page.locator('input[name="pswd"]').press('Tab');
  await page.getByRole('button', { name: 'Submit' }).press('Enter');
  await page.getByRole('button', { name: 'Timesheet' }).click();
  await page.getByRole('menuitem', { name: 'Timesheet Entry' }).click();
  await page.locator('#cmbTSEntry_SelectWeek-trigger-picker').click();
  await page.getByRole('option', { name: '-Jan-24 to 28-Jan-24 (N)' }).click();
  await page.locator('#tableview-1099-record-423 > tbody > .x-grid-row > td:nth-child(2) > .x-grid-cell-inner').click();
  await page.locator('#TSEntryGrd_cmbProject-trigger-picker').click();
  await page.getByRole('option', { name: 'Century Communities - Release' }).locator('div').click();
  await page.locator('#tableview-1099-record-423 > tbody > .x-grid-row > td:nth-child(4) > .x-grid-cell-inner').click();
  await page.locator('#ext-element-78').click();
  await page.locator('#combobox-1395-trigger-picker').click();
  await page.getByRole('option', { name: 'Build / Construction - Build Deployment/Sanity' }).click();
  await page.locator('#ext-element-85').click();
  await page.locator('#combobox-1396-trigger-picker').click();
  await page.getByRole('option', { name: 'Generic ETL process' }).click();
  await page.locator('td:nth-child(5) > .x-grid-cell-inner').first().click();
  await page.locator('#combobox-1401-trigger-picker').click();
  await page.getByRole('option', { name: 'ETL process updates' }).click();
  await page.locator('#combobox-1401-trigger-picker').click();
  await page.getByRole('option', { name: 'ETL process updates' }).click();
  await page.locator('td:nth-child(6) > .x-grid-cell-inner').first().click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('columnheader', { name: 'Remarks' }).click();
  await page.locator('td:nth-child(6) > .x-grid-cell-inner').first().click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('Hello');
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByText('Remarks', { exact: true }).click();
  await page.getByRole('gridcell', { name: 'Hello' }).locator('div').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click({
    clickCount: 3
  });
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('Remark');
  await page.getByText('Remarks', { exact: true }).click();
  await page.getByRole('columnheader', { name: 'Remarks' }).press('NumLock');
  await page.getByRole('gridcell', { name: 'Remark' }).locator('div').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').fill('Remarks');
  await page.locator('#tableview-1099').click();
  await page.locator('#ext-element-120').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('gridcell', { name: 'ETL process updates' }).locator('div').click();
  await page.locator('#ext-element-120').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.getByRole('row', { name: 'Century Communities - Release' }).getByLabel('').click();
  await page.locator('#ext-element-124').click();
  await page.locator('#combobox-1401-trigger-picker').click();
});